# Generated by Django 3.2.5 on 2021-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='1', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
